name = "PressureSensitiveMats"
uuid = "f7c67009-f2f2-4fe9-9b95-d54958a44a7b"
authors = ["Carter Green <carter.green@icloud.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
